# Generated by Django 5.0 on 2025-07-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_situation', models.CharField(default='Em Análise', max_length=30)),
                ('att_data_expire', models.DateField()),
                ('att_attached_by', models.CharField(max_length=100)),
                ('att_checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('att_data_conference', models.DateTimeField(blank=True, null=True)),
                ('att_data_inserted', models.DateTimeField(auto_now_add=True)),
                ('att_file', models.FileField(upload_to='pdfs/')),
                ('att_region', models.CharField(max_length=30)),
                ('att_state', models.CharField(max_length=2)),
                ('att_city', models.CharField(max_length=50)),
                ('att_doc', models.CharField(max_length=50)),
                ('att_center', models.CharField(max_length=50)),
                ('att_just', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('aud_id', models.AutoField(primary_key=True, serialize=False)),
                ('aud_action', models.CharField(max_length=30)),
                ('aud_obj_modified', models.CharField(max_length=30)),
                ('aud_description', models.CharField(default='-', max_length=256)),
                ('aud_data_inserted', models.DateTimeField(auto_now_add=True)),
                ('aud_login', models.CharField(max_length=100)),
                ('aud_profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_doc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False)),
                ('em_from', models.EmailField(blank=True, max_length=256, null=True)),
                ('em_email', models.EmailField(blank=True, max_length=256)),
                ('em_subject', models.CharField(max_length=128)),
                ('em_data_shipping', models.DateField(auto_now_add=True)),
                ('em_doc', models.CharField(max_length=256)),
                ('em_center', models.CharField(max_length=256)),
                ('em_login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('est_id', models.IntegerField(primary_key=True, serialize=False)),
                ('est_center', models.CharField(max_length=50)),
                ('est_region', models.CharField(blank=True, max_length=30, null=True)),
                ('est_state', models.CharField(max_length=2)),
                ('est_city', models.CharField(max_length=50)),
                ('est_address', models.CharField(max_length=256)),
                ('est_manage', models.CharField(default='-', max_length=30)),
                ('est_property', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstAux',
            fields=[
                ('estaux_id', models.AutoField(primary_key=True, serialize=False)),
                ('estaux_region', models.CharField(max_length=20)),
                ('estaux_uf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=256)),
                ('u_login', models.CharField(max_length=100)),
                ('u_password', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=256, unique=True)),
                ('u_status', models.CharField(default='Inativo', max_length=20)),
                ('u_time_in', models.DateField(auto_now_add=True)),
                ('u_time_out', models.DateField()),
                ('u_profile', models.CharField(choices=[('Sem Acesso', 'Sem Acesso'), ('Administrador', 'Administrador'), ('Auditor', 'Auditor'), ('Gerente Regional', 'Gerente Regional'), ('Usuário', 'Usuário')], default='Sem Acesso', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NumDocsEstab',
            fields=[
                ('ndest_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndest_units', models.CharField(max_length=20)),
                ('ndest_cnpj', models.CharField(default='-', max_length=18)),
                ('ndest_nire', models.CharField(default='-', max_length=11)),
                ('ndest_reg_city', models.CharField(default='-', max_length=20)),
                ('ndest_reg_state', models.CharField(default='-', max_length=20)),
                ('ndest_fk_establishment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='RelationCenterDoc',
            fields=[
                ('rcd_id', models.AutoField(primary_key=True, serialize=False)),
                ('rcd_fk_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.document')),
                ('rcd_fk_establishment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='RelationCenterUser',
            fields=[
                ('rcu_id', models.AutoField(primary_key=True, serialize=False)),
                ('rcu_center', models.CharField(default='-', max_length=50)),
                ('rcu_state', models.CharField(default='-', max_length=2)),
                ('rcu_region', models.CharField(default='-', max_length=30)),
                ('rcu_fk_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.users')),
            ],
        ),
    ]
