# Generated by Django 5.0 on 2025-08-03 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('sec_action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('WAF Block', 'Bloqueio WAF'), ('Session Hijack', 'Sequestro de Sessão'), ('IP Block', 'IP Bloqueado'), ('Other', 'Outro')], max_length=50)),
                ('sec_description', models.TextField()),
                ('sec_ip', models.GenericIPAddressField()),
                ('sec_user_agent', models.TextField(blank=True, null=True)),
                ('sec_payload', models.TextField(blank=True, null=True)),
                ('sec_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
