# Generated by Django 5.1.1 on 2025-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcenteruser',
            name='rcu_active',
            field=models.BooleanField(null=True),
        ),
    ]
