# Generated by Django 5.0 on 2025-08-11 06:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='sec_action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('WAF Block', 'Bloqueio WAF'), ('Session Hijack', 'Sequestro de Sessão'), ('IP Block', 'IP Bloqueado'), ('PDF Access', 'Acesso a PDF'), ('Other', 'Outro')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('d_doc'), name='uq_document_ddoc_lower'),
        ),
    ]
