# Generated by Django 5.1.1 on 2025-09-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relationcenteruser_rcu_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rs_q_emp',
            name='rs_q_estabnm',
        ),
    ]
