# Generated by Django 5.1.1 on 2025-09-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_rs_q_emp_rs_q_estabnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcenteruser',
            name='rcu_fk_estab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.establishment'),
        ),
    ]
