# Generated by Django 5.1.1 on 2025-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relationcenteruser_rcu_fk_estab'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationcenteruser',
            constraint=models.UniqueConstraint(fields=('rcu_fk_user', 'rcu_fk_estab'), name='uniq_rcu_user_estab'),
        ),
    ]
