# Generated by Django 5.1.1 on 2025-09-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_relationcenteruser_uniq_rcu_user_estab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationcenteruser',
            name='rcu_fk_estab',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='core.establishment'),
        ),
    ]
