# Generated by Django 5.1.1 on 2025-09-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_relationcenteruser_rcu_fk_estab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationcenteruser',
            name='rcu_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='relationcenteruser',
            name='rcu_fk_estab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.establishment'),
        ),
    ]
