# Generated by Django 5.1.1 on 2025-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_relationcenteruser_rcu_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PsDepartamento',
        ),
        migrations.DeleteModel(
            name='PsHierarUor',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='est_cnpj',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_cargo_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_admissao',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_atualiz',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_deslig',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_efetiva',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_escala',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_dt_nasc',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_escala_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_estab_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_funcao_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_gestor_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_local_id',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nm_estab',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nm_func',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nm_gestor',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nm_local',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nm_rel_empregaticia',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_nr_cnpj',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_sigla_depart',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_status',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_tp_rel_empregaticia',
        ),
        migrations.RemoveField(
            model_name='psfuncionario',
            name='func_uor_depart',
        ),
        migrations.AddField(
            model_name='rs_q_emp',
            name='rs_q_depen_sigla_uor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rs_q_emp',
            name='rs_q_depen_uor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rs_q_emp',
            name='rs_q_sigla_uor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rs_q_emp',
            name='rs_q_uor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='psfuncionario',
            name='func_nm_cargo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='psfuncionario',
            name='func_nm_funcao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_emplid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_estabid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
