# Generated by Django 5.1.1 on 2025-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_psdepartamento_delete_pshieraruor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_depen_sigla_uor',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rs_q_emp',
            name='rs_q_sigla_uor',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
